apiVersion: v1
kind: Service
metadata:
  name: paid-dapp-api
  labels:
    app: dapp-api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: dapp-api
  type: LoadBalancer
